name: Ronald Lovern
highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]
include: ["_pages"]
navigation: ["home", "refinish", "repair", "about", "contact"]
phone: 310-1010-4875
deal: no
company: Ronald Lovern
company-title: Bathtubs & Sinks - Repair & Refinish